[build]
  command = "./mvnw clean package -DskipTests"
  publish = "target"
  functions = "target/classes"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  JAVA_VERSION = "17"
  MAVEN_OPTS = "-Xmx1024m -XX:MaxMetaspaceSize=512m -XX:MaxPermSize=512m -XX:+UseContainerSupport -Dfile.encoding=UTF-8"
  NODE_VERSION = "16"

[functions]
  node_bundler = "esbuild"
